### ISSUE TITLE
com.amazonaws.AmazonServiceException: null (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: UnknownOperationException;

### ISSUE THREAD

**Issue by ivankixeye** [sharethrough/flume-kinesis#11]
I am getting a weird issue using the Firehose sink. I am running Flume on an Ubuntu 16.04 ec2 instance . I have confirmed I can `aws firehose put-record` successfully but I keep getting 400 when using the Firehose sink. Here is my flume.conf:
```
agg.sources = telnet
agg.sinks = es
agg.channels = ch

agg.channels.ch.type = memory
agg.channels.ch.capacity = 1000
agg.channels.ch.transactionCapacity = 100

agg.sources.telnet.type = netcat
agg.sources.telnet.bind = localhost
agg.sources.telnet.port = 44444
agg.sources.telnet.channels = ch

agg.sinks.es.type = com.amazonaws.services.kinesis.flume.FirehoseSink
agg.sinks.es.endpoint = https://kinesis.us-west-2.amazonaws.com
agg.sinks.es.streamName = my-delivery-stream
agg.sinks.es.channel = ch
```
Java version:
```
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)
```
I compiled flume-kinesis using source & target java versions 1.8.

Log from `./bin/flume-ng agent --conf conf --conf-file conf/flume.conf --name agg -Dflume.root.logger=DEBUG,console`:
```
2017-07-14 19:29:18,489 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:126)] Unable to load credentials from EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))
2017-07-14 19:29:18,489 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:126)] Unable to load credentials from SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey)
2017-07-14 19:29:18,490 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:126)] Unable to load credentials from com.amazonaws.auth.profile.ProfileCredentialsProvider@3398cc88: AWS credential profiles file not found in the given path: /root/.aws/credentials
2017-07-14 19:29:18,490 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.internal.EC2MetadataClient.readResource(EC2MetadataClient.java:84)] Connecting to EC2 instance metadata service at URL: http://169.254.169.254/latest/meta-data/iam/security-credentials/
2017-07-14 19:29:18,508 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.internal.EC2MetadataClient.readResource(EC2MetadataClient.java:84)] Connecting to EC2 instance metadata service at URL: http://169.254.169.254/latest/meta-data/iam/security-credentials/some-super-secret-iam-role
2017-07-14 19:29:18,558 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:119)] Loading credentials from InstanceProfileCredentialsProvider
2017-07-14 19:29:18,562 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:811)] Sending Request: POST https://kinesis.us-west-2.amazonaws.com / Headers: (User-Agent: aws-sdk-java/1.10.52 Linux/4.4.0-1022-aws OpenJDK_64-Bit_Server_VM/25.131-b11/1.8.0_131, amz-sdk-invocation-id: db8a6c10-285e-49a1-8c4c-f6f3ffaae55d, Content-Length: 196, X-Amz-Target: Firehose_20150804.PutRecordBatch, Content-Type: application/x-amz-json-1.1, ) 
2017-07-14 19:29:18,566 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.log.CommonsLog.debug(CommonsLog.java:33)] AWS4 Canonical Request: '"POST
/

amz-sdk-invocation-id:db8a6c10-285e-49a1-8c4c-f6f3ffaae55d
amz-sdk-retry:0/0
content-length:196
content-type:application/x-amz-json-1.1
host:kinesis.us-west-2.amazonaws.com
user-agent:aws-sdk-java/1.10.52 Linux/4.4.0-1022-aws OpenJDK_64-Bit_Server_VM/25.131-b11/1.8.0_131
x-amz-date:20170714T192918Z
x-amz-security-token:secret//////////secret=
x-amz-target:Firehose_20150804.PutRecordBatch

amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-security-token;x-amz-target
f83f8683be6bb728b98bc012f6ff1415c487d7cc70c677bde30cf7491266c00c"
2017-07-14 19:29:18,566 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.log.CommonsLog.debug(CommonsLog.java:33)] AWS4 String to Sign: '"AWS4-HMAC-SHA256
20170714T192918Z
20170714/us-west-2/firehose/aws4_request
85ad1ab8aad484736371bcf93578b880da4c5fe28b2c933cdb1a654cdefd7413"
2017-07-14 19:29:18,567 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.log.CommonsLog.debug(CommonsLog.java:33)] Generating a new signing key as the signing key not available in the cache for the date 1499990400000
2017-07-14 19:29:18,603 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.PoolingClientConnectionManager.requestConnection(PoolingClientConnectionManager.java:182)] Connection request: [route: {s}->https://kinesis.us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-07-14 19:29:18,611 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:214)] Connection leased: [id: 0][route: {s}->https://kinesis.us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 1 of 50; total allocated: 1 of 50]
2017-07-14 19:29:18,617 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.prepareSocket(SdkTLSSocketFactory.java:79)] socket.getSupportedProtocols(): [SSLv2Hello, SSLv3, TLSv1, TLSv1.1, TLSv1.2], socket.getEnabledProtocols(): [TLSv1, TLSv1.1, TLSv1.2]
2017-07-14 19:29:18,618 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.prepareSocket(SdkTLSSocketFactory.java:107)] TLS protocol enabled for SSL handshake: [TLSv1.2, TLSv1.1, TLSv1]
2017-07-14 19:29:18,618 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:174)] Connecting to kinesis.us-west-2.amazonaws.com:443
2017-07-14 19:29:18,618 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:131)] connecting to kinesis.us-west-2.amazonaws.com/52.94.209.34:443
2017-07-14 19:29:18,715 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.internal.SdkSSLSocket.<init>(SdkSSLSocket.java:31)] created: kinesis.us-west-2.amazonaws.com/52.94.209.34:443
2017-07-14 19:29:18,726 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.client.protocol.RequestAddCookies.process(RequestAddCookies.java:122)] CookieSpec selected: default
2017-07-14 19:29:18,727 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.client.protocol.RequestAuthCache.process(RequestAuthCache.java:76)] Auth cache not set in the context
2017-07-14 19:29:18,727 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.client.protocol.RequestProxyAuthentication.process(RequestProxyAuthentication.java:87)] Proxy auth state: UNCHALLENGED
2017-07-14 19:29:18,727 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:683)] Attempt 1 to execute request
2017-07-14 19:29:18,727 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:268)] Sending request: POST / HTTP/1.1
2017-07-14 19:29:18,728 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "POST / HTTP/1.1[\r][\n]"
2017-07-14 19:29:18,729 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "Host: kinesis.us-west-2.amazonaws.com[\r][\n]"
2017-07-14 19:29:18,729 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "Authorization: AWS4-HMAC-SHA256 Credential=secret/20170714/us-west-2/firehose/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-security-token;x-amz-target, Signature=secret[\r][\n]"
2017-07-14 19:29:18,729 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "X-Amz-Date: 20170714T192918Z[\r][\n]"
2017-07-14 19:29:18,730 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "User-Agent: aws-sdk-java/1.10.52 Linux/4.4.0-1022-aws OpenJDK_64-Bit_Server_VM/25.131-b11/1.8.0_131[\r][\n]"
2017-07-14 19:29:18,730 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "X-Amz-Security-Token: secret//////////secret=[\r][\n]"
2017-07-14 19:29:18,731 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "amz-sdk-invocation-id: db8a6c10-285e-49a1-8c4c-f6f3ffaae55d[\r][\n]"
2017-07-14 19:29:18,731 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "amz-sdk-retry: 0/0[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "X-Amz-Target: Firehose_20150804.PutRecordBatch[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "Content-Type: application/x-amz-json-1.1[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "Content-Length: 196[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "Connection: Keep-Alive[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  >> "[\r][\n]"
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:272)] >> POST / HTTP/1.1
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> Host: kinesis.us-west-2.amazonaws.com
2017-07-14 19:29:18,732 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> Authorization: AWS4-HMAC-SHA256 Credential=secret/20170714/us-west-2/firehose/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-security-token;x-amz-target, Signature=secret
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> X-Amz-Date: 20170714T192918Z
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> User-Agent: aws-sdk-java/1.10.52 Linux/4.4.0-1022-aws OpenJDK_64-Bit_Server_VM/25.131-b11/1.8.0_131
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> X-Amz-Security-Token: secret//////////secret=
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> amz-sdk-invocation-id: db8a6c10-285e-49a1-8c4c-f6f3ffaae55d
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> amz-sdk-retry: 0/0
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> X-Amz-Target: Firehose_20150804.PutRecordBatch
2017-07-14 19:29:18,733 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> Content-Type: application/x-amz-json-1.1
2017-07-14 19:29:18,734 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> Content-Length: 196
2017-07-14 19:29:18,734 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.sendRequestHeader(DefaultClientConnection.java:275)] >> Connection: Keep-Alive
2017-07-14 19:29:18,734 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:86)]  >> "{"DeliveryStreamName":"my-delivery-stream","Records":[{"Data":"YXNkZmFzZGZzZGZhc2RmbGphc2Rmc2pkbGZzZGFmbGRqZmtzZGFmYXNkbGZqbGFzZGZqa2xzZGZqbHNkZmthc2RrbGZqbGtzYWZqa2xhc2RqZmxza2RqZmxrYXNkDQ=="}]}"
2017-07-14 19:29:18,742 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "HTTP/1.1 400 Bad Request[\r][\n]"
2017-07-14 19:29:18,743 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "Server: Apache-Coyote/1.1[\r][\n]"
2017-07-14 19:29:18,743 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "x-amzn-RequestId: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "x-amz-id-2: Ol9BhEuvWSKdBhOZ/j5zRLHi8EFty1mQ6TzVoyoy3fiPIQGTqQ4Dlzc7vaHhLf69DRSla1zCFNf1QTvaE/PPFTeuEparRr59[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "Content-Type: application/x-amz-json-1.1[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "Content-Length: 38[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "Date: Fri, 14 Jul 2017 19:29:18 GMT[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "Connection: close[\r][\n]"
2017-07-14 19:29:18,744 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:72)]  << "[\r][\n]"
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:253)] Receiving response: HTTP/1.1 400 Bad Request
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:256)] << HTTP/1.1 400 Bad Request
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << Server: Apache-Coyote/1.1
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << x-amzn-RequestId: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << x-amz-id-2: Ol9BhEuvWSKdBhOZ/j5zRLHi8EFty1mQ6TzVoyoy3fiPIQGTqQ4Dlzc7vaHhLf69DRSla1zCFNf1QTvaE/PPFTeuEparRr59
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << Content-Type: application/x-amz-json-1.1
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << Content-Length: 38
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << Date: Fri, 14 Jul 2017 19:29:18 GMT
2017-07-14 19:29:18,745 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:259)] << Connection: close
2017-07-14 19:29:18,758 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.AmazonHttpClient.logHeaderRequestId(AmazonHttpClient.java:997)] x-amzn-RequestId: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1
2017-07-14 19:29:18,766 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.Wire.wire(Wire.java:86)]  << "{"__type":"UnknownOperationException"}"
2017-07-14 19:29:18,767 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.internal.SdkSSLSocket.shutdownOutput(SdkSSLSocket.java:76)] shutting down output of kinesis.us-west-2.amazonaws.com/52.94.209.34:443
2017-07-14 19:29:18,767 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.internal.SdkSSLSocket.close(SdkSSLSocket.java:62)] closing kinesis.us-west-2.amazonaws.com/52.94.209.34:443
2017-07-14 19:29:18,767 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.DefaultClientConnection.close(DefaultClientConnection.java:176)] Connection 0.0.0.0:51194<->52.94.209.34:443 closed
2017-07-14 19:29:18,768 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - shaded.org.apache.http.impl.conn.PoolingClientConnectionManager.releaseConnection(PoolingClientConnectionManager.java:269)] Connection released: [id: 0][route: {s}->https://kinesis.us-west-2.amazonaws.com:443][total kept alive: 0; route allocated: 0 of 50; total allocated: 0 of 50]
2017-07-14 19:29:18,780 (SinkRunner-PollingRunner-DefaultSinkProcessor) [DEBUG - com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1340)] Received error response: com.amazonaws.AmazonServiceException: null (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: UnknownOperationException; Request ID: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1)
2017-07-14 19:29:18,780 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - com.amazonaws.services.kinesis.flume.FirehoseSink.process(FirehoseSink.java:177)] Failed to commit transaction. Transaction rolled back.
com.amazonaws.AmazonServiceException: null (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: UnknownOperationException; Request ID: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1369)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311)
        at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(AmazonKinesisFirehoseClient.java:940)
        at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.putRecordBatch(AmazonKinesisFirehoseClient.java:784)
        at com.amazonaws.services.kinesis.flume.FirehoseSink.process(FirehoseSink.java:138)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:67)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145)
        at java.lang.Thread.run(Thread.java:748)
2017-07-14 19:29:18,781 (SinkRunner-PollingRunner-DefaultSinkProcessor) [ERROR - org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:158)] Unable to deliver event. Exception follows.
org.apache.flume.EventDeliveryException: com.amazonaws.AmazonServiceException: null (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: UnknownOperationException; Request ID: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1)
        at com.amazonaws.services.kinesis.flume.FirehoseSink.process(FirehoseSink.java:182)
        at org.apache.flume.sink.DefaultSinkProcessor.process(DefaultSinkProcessor.java:67)
        at org.apache.flume.SinkRunner$PollingRunner.run(SinkRunner.java:145)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.AmazonServiceException: null (Service: AmazonKinesisFirehose; Status Code: 400; Error Code: UnknownOperationException; Request ID: d83bfc5a-3cd3-d9ef-89d8-e194103f26d1)
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1369)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:913)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:631)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:400)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:362)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:311)
        at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.invoke(AmazonKinesisFirehoseClient.java:940)
        at com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.putRecordBatch(AmazonKinesisFirehoseClient.java:784)
        at com.amazonaws.services.kinesis.flume.FirehoseSink.process(FirehoseSink.java:138)
        ... 3 more
```
I must be missing something obvious?

**Comment by ivankixeye** [comment]
Hi Russel, that fixed my problem thank you!
